apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-efs-csi-driver
spec:
  releaseName: aws-efs-csi-driver
  values:
    # Values are overridden by these
    replicaCount: 2

    image:
      repository: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/aws-efs-csi-driver
      tag: "v1.3.3"
      pullPolicy: IfNotPresent

    ## Controller deployment variables
    controller:
      # Specifies whether a service account should be created
      serviceAccount:
        create: false
        name: efs-csi-controller-sa
        #annotations: {}
        ## Enable if EKS IAM for SA is used
        #  eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/efs-csi-role

    storageClasses: 
    # Add StorageClass resources like:
      - name: efs-sc
    #   annotations:
    #     # Use that annotation if you want this to your default storageclass
    #     storageclass.kubernetes.io/is-default-class: "true"
        mountOptions:
         - tls
    #   parameters:
    #     provisioningMode: efs-ap
    #     fileSystemId: fs-1122aabb
    #     directoryPerms: "700"
    #     gidRangeStart: "1000"
    #     gidRangeEnd: "2000"
    #     basePath: "/dynamic_provisioning"
        reclaimPolicy: Delete
        volumeBindingMode: Immediate