---
apiVersion: v1
kind: Namespace
metadata:
  name: ${example_namespace}
  labels:
    mesh: ${example_namespace}-mesh
    gateway: ingress-gw
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
  annotations:
    # annotation key is configurable
    externalsecrets.kubernetes-client.io/permitted-key-name: "/${cluster_env}/${cluster_name}/${example_namespace}/.*"

