---
# The ./clusters/<cluster-name>/examples.yaml specifies the value for example_namespace. e.g. 'example'
# Create the example_namespace with needed lables to support AWS Appmesh and annotations to support Kubernetes External Secrets.
# These labels and annotations will be required in each application namespace that requie AWS Appmesh and Kubernetes External Secrets.
apiVersion: v1
kind: Namespace
metadata:
  name: ${example_namespace}
  labels:
    mesh: ${example_namespace}-mesh
    gateway: ingress-gw
    appmesh.k8s.aws/sidecarInjectorWebhook: enabled
  annotations:
    # annotation key is configurable
    externalsecrets.kubernetes-client.io/permitted-key-name: "/${cluster_env}/${cluster_name}-eks-cluster/${example_namespace}/.*"

