apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amazon-cloudwatch
resources:
  - namespace.yaml
  - serviceaccount.yaml
  #- cwa-prometheus-cm.yaml
  #- cwa-prometheus.yaml
  