---
# create cwagent service account and role binding
# if service account is already defined, change the binding here
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatch-agent
  namespace: amazon-cloudwatch