---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: red
  namespace: ${ks_namespace}
spec:
  podSelector:
    matchLabels:
      app: color
      version: red
  listeners:
    - portMapping:
        port: 9080
        protocol: http
      healthCheck:
        protocol: http
        path: "/ping"
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 5000
  serviceDiscovery:
    dns:
      hostname: color-red.${ks_namespace}.svc.cluster.local
  logging:
    accessLog:
      file:
        path: "/dev/stdout"
---
apiVersion: v1
kind: Service
metadata:
  name: color-red
  namespace: ${ks_namespace}
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: color
    version: red
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  namespace: ${ks_namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color
      version: red
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: ${ks_namespace}-mesh
      labels:
        app: color
        version: red
    spec:
      serviceAccount: appmesh-pod
      containers:
        - name: app
          image: "${appmesh_color_demo_image}"
          ports:
            - containerPort: 9080
          env:
            - name: "COLOR"
              value: "red"
            - name: "PORT"
              value: "9080"
---