---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: green
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: color
      version: green
  listeners:
    - portMapping:
        port: 9080
        protocol: http
      healthCheck:
        protocol: http
        path: "/ping"
        healthyThreshold: 2
        unhealthyThreshold: 2
        timeoutMillis: 2000
        intervalMillis: 5000
  serviceDiscovery:
    dns:
      hostname: color-green.default.svc.cluster.local
  logging:
    accessLog:
      file:
        path: "/dev/stdout"
---
apiVersion: v1
kind: Service
metadata:
  name: color-green
  namespace: default
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: color
    version: green
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color
      version: green
  template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: default-mesh
      labels:
        app: color
        version: green
    spec:
      serviceAccount: appmesh-pod
      containers:
        - name: app
          image: "vivekgoyal/colorapp"
          ports:
            - containerPort: 9080
          env:
            - name: "COLOR"
              value: "green"
            - name: "PORT"
              value: "9080"
---