---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: appmesh-prometheus
    app.kubernetes.io/name: appmesh-prometheus
  #annotations:
  #  kustomize.toolkit.fluxcd.io/prune: disabled
  name: appmesh-prometheus
  namespace: appmesh-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: appmesh-prometheus
      app.kubernetes.io/name: appmesh-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: appmesh-prometheus
        app.kubernetes.io/name: appmesh-prometheus
    spec:
      containers:
        - name: appmesh-prometheus
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
