---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appmesh-prometheus
  namespace: appmesh-system
spec:
  template:
    spec:
      containers:
        - name: appmesh-prometheus
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
