apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger 
spec:
  releaseName: flagger 
  values:
    metricsServer: "http://appmesh-prometheus:9090"
    #metricsServer: ""

    # accepted values are kubernetes, istio, linkerd, appmesh, contour, nginx, gloo, skipper, traefik, osm
    meshProvider: "appmesh:v1beta2"
