apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appmesh-system
resources:
  - https://github.com/aws/eks-charts/stable/appmesh-controller//crds?ref=master
  - release.yaml
patchesStrategicMerge:
  - values.yaml