apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: appmesh-system
resources:
  - https://github.com/aws/eks-charts/stable/appmesh-controller//crds?ref=master
  - appmesh-controller.yaml
  - prometheus-storage.yaml
  - appmesh-prometheus.yaml
  - https://raw.githubusercontent.com/fluxcd/flagger/main/artifacts/flagger/crd.yaml
  - flagger.yaml
patchesStrategicMerge:
  - appmesh-controller-values.yaml
  - appmesh-prometheus-values.yaml  
  #- appmesh-prometheus-patch.yaml
  - flagger-values.yaml  
  #- |-
  #  apiVersion: apps/v1
  #  kind: Deployment
  #  metadata:
  #    name: appmesh-prometheus
  #    namespace: appmesh-system
  #  spec:
  #    template:
  #      spec:
  #        containers:
  #          - name: appmesh-prometheus
  #            livenessProbe:
  #              failureThreshold: 3
  #              initialDelaySeconds: 120
  #              periodSeconds: 10
  #              successThreshold: 1
  #              timeoutSeconds: 1
  #            readinessProbe:
  #              failureThreshold: 3
  #              initialDelaySeconds: 120
  #              periodSeconds: 10
  #              successThreshold: 1
  #              timeoutSeconds: 1
#patches:
#- path: appmesh-prometheus-patch.yaml
#  target:
#    kind: Deployment
#    name: appmesh-prometheus
#    namespace: appmesh-system
    #labelSelector: "app.kubernetes.io/instance=appmesh-prometheus,app.kubernetes.io/name: appmesh-prometheus"
