apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger-loadtester
spec:
  releaseName: flagger-loadtester
  chart:
    spec:
      chart: loadtester
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    serviceAccountName: "appmesh-pod"
    # App Mesh virtual node settings (to be used for AppMesh v1beta2)
    appmesh:
      enabled: true
      backends:
        - podinfo
        - podinfo-canary
