---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: "${example_namespace}-secrets"
spec:
  backendType: secretsManager
  dataFrom:
    - /${cluster_env}/${cluster_name}-eks-cluster/${example_namespace}/hello-service/secrets
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: "${example_namespace}-params"
spec:
  backendType: systemManager
  dataFrom:
    - /${cluster_env}/${cluster_name}-eks-cluster/${example_namespace}/hello-service/params
---
# ExternalSecrets from other namespace should fail
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: some-ns-secrets
spec:
  backendType: secretsManager
  dataFrom:
    - /${cluster_env}/${cluster_name}-eks-cluster/some-ns/hello-service/secrets
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: some-ns-params
spec:
  backendType: systemManager
  dataFrom:
    - /${cluster_env}/${cluster_name}-eks-cluster/some-ns/hello-service/params