---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: "${ks_namespace}-secrets"
spec:
  backendType: secretsManager
  dataFrom:
    - /${cluster_env}/${cluster_name}/${ks_namespace}/hello-service/secrets
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: "${ks_namespace}-params"
spec:
  backendType: systemManager
  dataFrom:
    - /${cluster_env}/${cluster_name}/${ks_namespace}/hello-service/params
---
# ExternalSecrets from other namespace should fail
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: some-ns-secrets
spec:
  backendType: secretsManager
  dataFrom:
    - /${cluster_env}/${cluster_name}/some-ns/hello-service/secrets
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: some-ns-params
spec:
  backendType: systemManager
  dataFrom:
    - /${cluster_env}/${cluster_name}/some-ns/hello-service/params