apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: examples
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./examples/devops
  prune: true
  validation: client
  postBuild:
    substitute:
      cluster_env: "devops"
      cluster_name: "devops"
      example_namespace: "example"
      appmesh_color_demo_image: "vivekgoyal/colorapp:appmeshdemo"
