apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure
  prune: true
  validation: client
  postBuild:
    substitute:
      #true of false does not matter, there has to be at least one variable
      var_substitution_enabled: "true"
      cluster_env: "dev"
      cluster_name: "devops"
      cluster_account: "007826922078"
      cluster_region: "us-west-2"
      cluster_vpc: "vpc-670e3100"
      cluster_efs_handle: "fs-4404cd42"
